[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "crypto>=1.4.1",
    "flask-talisman>=1.1.0",
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
    "flask-seasurf>=2.0.0",
]
